[package]
name = "MoneyMarket"
version = "0.0.1"
published-at = "0x48466dc11f9ccb87b4081ac7ee5cd9ead3a5c2db97a0fb49c8d3c2df1ecdaf07"

[dependencies.Sui]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/sui-framework"
rev = "testnet-v1.4.1"
override = true

[dependencies.MoveStdlib]
git = "https://github.com/MystenLabs/sui.git"
subdir = "crates/sui-framework/packages/move-stdlib"
rev = "testnet-v1.4.1"
override = true

[dependencies]
Oracle = { local = "../oracle"}
Library = { local = "../library" }
SuiDollar = { local = "../sui-dollar" }
IPX = { local = "./dependencies/ipx" }

[addresses]
money_market = "0x48466dc11f9ccb87b4081ac7ee5cd9ead3a5c2db97a0fb49c8d3c2df1ecdaf07"
std = "0x1"
sui =  "0x2"
treasury = "0xCAFE"
sui_dollar =  "0x02871464ed71b80969b32f2b23c981b085866485ba5368c0f59588fcc0dbce47"
ipx =  "0xd85ff9aaebfb24f6cd8b5e89afcda7ad317f07ed6f8a322d72dca22c8c8c47a4"
oracle = "0xbd5fc6e8494555f8f01e8b75e920532b560b7a71eabd439aa2d0dbeae7b81653"
library = "0x4c24b307b94457f1a66bae100ef3bfd38c2cbf44ba1a2124337dd828916c5135"